steps:
  # Step 1: Build the container image using Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/letterboxdwebscraper:$COMMIT_SHA', '.']

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/letterboxdwebscraper:$COMMIT_SHA']

  # Step 3: Deploy the container image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'shinoda'
      - '--image'
      - 'gcr.io/$PROJECT_ID/letterboxdwebscraper:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/letterboxdwebscraper:$COMMIT_SHA'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY